name: ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          # Match all .sh files and hidden dotfiles
          additional_files: '^.*\.sh$ ^bash\/\.bashrc$'
        env:
          # Specify severity threshold if desired (error, warning, info, style)
          SHELLCHECK_OPTS: -s bash
